language: node_js
sudo: required
cache:
  directories:
  - node_modules
node_js:
- "8"
script:
- npm install
- npm build
- cp .travis.yml build
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
  local-dir: build
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master